on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: "Super Linter"
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: "/"
          VALIDATE_ANSIBLE: false
        shell: bash
        run: |
          docker pull github/super-linter:latest
          docker run -e RUN_LOCAL=true -v ${GITHUB_WORKSPACE}:/tmp/lint github/super-linter
